// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC62G9_beAH3YxHbU3fcxlW5KUrVokefKo',
    appId: '1:1944382428:web:64caa238f8cad9cf34bd19',
    messagingSenderId: '1944382428',
    projectId: 'nextpass-3be78',
    authDomain: 'nextpass-3be78.firebaseapp.com',
    storageBucket: 'nextpass-3be78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEt-_LLHOId8WlnOi0CFkFGhTm0tODvFA',
    appId: '1:1944382428:android:1d263af3242163ce34bd19',
    messagingSenderId: '1944382428',
    projectId: 'nextpass-3be78',
    storageBucket: 'nextpass-3be78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWrOR9YWrn7u6pLA0zhQlUWZD3Uw-taaQ',
    appId: '1:1944382428:ios:f8824762c9c472d534bd19',
    messagingSenderId: '1944382428',
    projectId: 'nextpass-3be78',
    storageBucket: 'nextpass-3be78.appspot.com',
    iosBundleId: 'com.example.passwordmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWrOR9YWrn7u6pLA0zhQlUWZD3Uw-taaQ',
    appId: '1:1944382428:ios:f8824762c9c472d534bd19',
    messagingSenderId: '1944382428',
    projectId: 'nextpass-3be78',
    storageBucket: 'nextpass-3be78.appspot.com',
    iosBundleId: 'com.example.passwordmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC62G9_beAH3YxHbU3fcxlW5KUrVokefKo',
    appId: '1:1944382428:web:9dcfde16dba2209b34bd19',
    messagingSenderId: '1944382428',
    projectId: 'nextpass-3be78',
    authDomain: 'nextpass-3be78.firebaseapp.com',
    storageBucket: 'nextpass-3be78.appspot.com',
  );

}